Cs/note updates
TheFunGroup/fun-wallet-test-react pull request #1
Opened 2023-01-13 01:05 UTC by Mario-Fun

2023-01-14 03:52 UTC, AlexFine commented
Two general comments here: 

1. Readme Update. We need to update the readme here away from the React template. 
2. Clearer file structure. To an outside developer the file structure is unclear. As a web2 developer I immediately go to the `index.js`, however, that file does not seem to be the relevant file. Perhaps improved documentation would fix this issue. 

Difficult for me to judge in more detail until these two topics are addressed.

2023-01-14 03:54 UTC, AlexFine commented
Some implementation comments: 

- Commit language. We need to improve the clarity of code commits. Current commits are not descriptive or informative. This reflects poorly on us as an organization, and does not induce trust. We need an extreme attention to detail on every part of the codebase. Customers are trusting us with their money. That is hugely important.

2023-01-16 22:23 UTC, mariobaxter requested changes

2023-01-16 22:23 UTC, mariobaxter commented on src/App.js
> +  // }, [pkey])
remove comments

2023-01-16 22:23 UTC, mariobaxter commented on src/App.js
> -    // const eoa = new ethers.Wallet(privKey, provider)
Remove comments

2023-01-16 22:23 UTC, mariobaxter commented on src/App.js
> +    const prefundAmt = 0 // eth
Should be 0.3?

2023-01-16 22:23 UTC, mariobaxter commented on src/App.js
> +    const chain = '43113'
Should be a global variable

2023-01-16 23:21 UTC, merged